### ISSUE TITLE
Minimum Python version is 3.9

### ISSUE THREAD

**Issue by schlegelp** [connectome-neuprint/neuprint-python#49]
Hi Stuart!

I had a lab member report the following error:

```python
>>> t = neu.fetch_neurons(10098)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bellabeckett/opt/miniconda3/envs/venv_38/lib/python3.8/site-packages/neuprint/client.py", line 240, in wrapper
    return f(*args, **kwargs, client=client)
  File "/Users/bellabeckett/opt/miniconda3/envs/venv_38/lib/python3.8/site-packages/neuprint/queries/neuroncriteria.py", line 36, in wrapper
    return f(**callargs)
  File "/Users/bellabeckett/opt/miniconda3/envs/venv_38/lib/python3.8/site-packages/neuprint/queries/neurons.py", line 126, in fetch_neurons
    {criteria.all_conditions(prefix=8)}
  File "/Users/bellabeckett/opt/miniconda3/envs/venv_38/lib/python3.8/site-packages/neuprint/queries/neuroncriteria.py", line 855, in all_conditions
    basic_cond = self.basic_conditions(0, comments)
  File "/Users/bellabeckett/opt/miniconda3/envs/venv_38/lib/python3.8/site-packages/neuprint/queries/neuroncriteria.py", line 926, in basic_conditions
    exprs = self.basic_exprs()
  File "/Users/bellabeckett/opt/miniconda3/envs/venv_38/lib/python3.8/site-packages/neuprint/queries/neuroncriteria.py", line 729, in basic_exprs
    exprs |= {
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
```

It looks like the latest version of `neuprint-python`  is using the `|=` union operator for combining dictionaries. This was introduced in Python 3.9 but the `setup.py` doesn't specify a minimum Python version yet. 

Best,
Philipp

**Comment by markuspleijzier** [comment]
just FYI, I also ran into this bug today

**Comment by stuarteberg** [comment]
@markuspleijzier Is Python 3.9 a problem for you?  If so, I can look into supporting older Python versions.  [Python 3.8 isn't officially dead until next year.][1]

[1]: https://devguide.python.org/versions/

**Comment by markuspleijzier** [comment]
@stuarteberg works fine for me in Python 3.9
